"""add evaluacion_riesgo

Revision ID: 1dc6b5224824
Revises: 45e5fa6e8a5e
Create Date: 2026-05-18 18:52:02.867759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc6b5224824'
down_revision = '45e5fa6e8a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluacion_riesgo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('probabilidad_ansiedad', sa.Float(), nullable=True),
    sa.Column('categoria_riesgo', sa.String(length=20), nullable=True),
    sa.Column('explicacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluacion_riesgo')
    # ### end Alembic commands ###
