"""Agregadas 9 variables psicometricas al modelo de usuario

Revision ID: 45e5fa6e8a5e
Revises: 52a7ded3ef95
Create Date: 2026-05-18 17:46:12.427040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e5fa6e8a5e'
down_revision = '52a7ded3ef95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phq9', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gad7', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('online_stress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('financial_stress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('academic_stress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gpa', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('family_support', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('self_efficacy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('peer_relationship', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('peer_relationship')
        batch_op.drop_column('self_efficacy')
        batch_op.drop_column('family_support')
        batch_op.drop_column('gpa')
        batch_op.drop_column('academic_stress')
        batch_op.drop_column('financial_stress')
        batch_op.drop_column('online_stress')
        batch_op.drop_column('gad7')
        batch_op.drop_column('phq9')

    # ### end Alembic commands ###
