"""init

Revision ID: 52a7ded3ef95
Revises: 
Create Date: 2026-05-15 21:40:17.338422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a7ded3ef95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "rol", sa.String(length=20), nullable=False, server_default="Estudiante"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
