"""Esquema oficial: usuarios, evaluacion, resultados_ml, recomendaciones

Revision ID: dd12ce3ce73f
Revises: 
Create Date: 2026-05-22 04:01:23.773181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd12ce3ce73f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recomendaciones',
    sa.Column('id_recomendacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_recomendacion')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('facultad', sa.String(length=100), nullable=True),
    sa.Column('ciclo', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('evaluacion',
    sa.Column('id_evaluacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_realizacion', sa.DateTime(), nullable=True),
    sa.Column('phq9_score', sa.Float(), nullable=False),
    sa.Column('gad7_score', sa.Float(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=False),
    sa.Column('exercise_freq', sa.Float(), nullable=False),
    sa.Column('social_activity', sa.Float(), nullable=False),
    sa.Column('online_stress', sa.Float(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.Column('family_support', sa.Float(), nullable=False),
    sa.Column('screen_time', sa.Float(), nullable=False),
    sa.Column('academic_stress', sa.Float(), nullable=False),
    sa.Column('diet_quality', sa.Float(), nullable=False),
    sa.Column('self_efficacy', sa.Float(), nullable=False),
    sa.Column('peer_relationship', sa.Float(), nullable=False),
    sa.Column('financial_stress', sa.Float(), nullable=False),
    sa.Column('sleep_quality', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_evaluacion')
    )
    op.create_table('resultados_ml',
    sa.Column('id_resultado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_evaluacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('probabilidad_ansiedad', sa.Float(), nullable=False),
    sa.Column('nivel_riesgo', sa.String(length=20), nullable=False),
    sa.Column('fecha_prediccion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_evaluacion'], ['evaluacion.id_evaluacion'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_resultado'),
    sa.UniqueConstraint('id_evaluacion')
    )
    op.create_table('resultado_recomendaciones',
    sa.Column('id_resultado', sa.Integer(), nullable=False),
    sa.Column('id_recomendacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_recomendacion'], ['recomendaciones.id_recomendacion'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_resultado'], ['resultados_ml.id_resultado'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_resultado', 'id_recomendacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultado_recomendaciones')
    op.drop_table('resultados_ml')
    op.drop_table('evaluacion')
    op.drop_table('usuarios')
    op.drop_table('recomendaciones')
    # ### end Alembic commands ###
